apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
  namespace: dev
data:
  DEBUG: "True"
  DATABASE_URL: "postgres://django_user:django_pass@postgres:5432/django_db"
  REDIS_URL: "redis://redis:6379"
  ALLOWED_HOSTS: "*"